// Seed data. Everything here is fabricated for the demo: sellers, listings,
// ratings, sales counts and cert numbers are synthetic. Coin photos are
// public-domain images from Wikimedia Commons; card images are generated
// placeholders, never real card art.
import type { Listing, Persona, Seller } from './types.js'

export const PERSONAS: Persona[] = [
  { id: 'alex', name: 'Alex Rivera', email: 'alex@example.com', kind: 'collector' },
  { id: 'mike', name: 'Mike Chen', email: 'mike@example.com', kind: 'collector' },
  { id: 'admin', name: 'Slabbed Admin', email: 'admin@example.com', kind: 'admin' },
]

export const SELLERS: Seller[] = [
  {
    id: 'alex',
    handle: 'alexr_collects',
    rating: 5.0,
    sales: 0,
    joinedYear: 2026,
    shipsFrom: 'Austin, TX',
  },
  {
    id: 'mike',
    handle: 'mikec_numis',
    rating: 4.9,
    sales: 142,
    joinedYear: 2019,
    shipsFrom: 'San Jose, CA',
  },
  {
    id: 'sel_bluesheet',
    handle: 'bluesheet_bullion',
    rating: 4.8,
    sales: 611,
    joinedYear: 2016,
    shipsFrom: 'Columbus, OH',
  },
  {
    id: 'sel_carsoncity',
    handle: 'carsoncity_kid',
    rating: 4.6,
    sales: 87,
    joinedYear: 2021,
    shipsFrom: 'Reno, NV',
  },
  {
    id: 'sel_wheatieshunter',
    handle: 'wheaties_hunter',
    rating: 4.4,
    sales: 39,
    joinedYear: 2023,
    shipsFrom: 'Des Moines, IA',
  },
  {
    id: 'sel_doubleeagle',
    handle: 'double_eagle_desk',
    rating: 5.0,
    sales: 58,
    joinedYear: 2018,
    shipsFrom: 'Charlotte, NC',
  },
  {
    id: 'sel_rookiecards',
    handle: 'rookie_card_room',
    rating: 4.7,
    sales: 320,
    joinedYear: 2020,
    shipsFrom: 'Philadelphia, PA',
  },
  {
    id: 'sel_hoopslabs',
    handle: 'hoops_slabs',
    rating: 4.2,
    sales: 24,
    joinedYear: 2024,
    shipsFrom: 'Chicago, IL',
  },
  {
    id: 'sel_holofoil',
    handle: 'holofoil_vault',
    rating: 4.9,
    sales: 455,
    joinedYear: 2017,
    shipsFrom: 'Seattle, WA',
  },
  {
    id: 'sel_attictreasure',
    handle: 'attic_find_tom',
    rating: 4.5,
    sales: 12,
    joinedYear: 2025,
    shipsFrom: 'Tampa, FL',
  },
]

const esc = (s: string) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')

/** A generic graded-slab placeholder: label band (grader + grade) over the title. */
function slabSvg(title: string, label: string): string {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 300 420" width="300" height="420">
<rect x="6" y="6" width="288" height="408" rx="10" fill="#e9e6df" stroke="#9a968d" stroke-width="3"/>
<rect x="20" y="20" width="260" height="70" rx="4" fill="#1f2a44"/>
<text x="150" y="52" font-family="Arial,sans-serif" font-size="22" font-weight="700" fill="#fff" text-anchor="middle">${esc(label)}</text>
<text x="150" y="76" font-family="Arial,sans-serif" font-size="11" fill="#c9cfdc" text-anchor="middle">SAMPLE SLAB</text>
<rect x="40" y="106" width="220" height="290" rx="4" fill="#f7f5f0" stroke="#bdb8ad"/>
<text x="150" y="250" font-family="Arial,sans-serif" font-size="14" fill="#333" text-anchor="middle">${esc(title)}</text>
</svg>`
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
}

type CardSeed = Omit<Listing, 'imageUrl' | 'category'> & { short: string }
const card = ({ short, ...l }: CardSeed): Listing => ({
  ...l,
  category: 'card',
  imageUrl: slabSvg(short, l.graded ? `${l.grade}` : 'RAW'),
})

// Coin photos are public-domain images from Wikimedia Commons, vendored locally in
// public/listings/ so the storefront doesn't hotlink a remote host.
export const LISTINGS: Listing[] = [
  // ── Coins ────────────────────────────────────────────────────────────────
  {
    id: 'lst_001',
    sellerId: 'mike',
    category: 'coin',
    title: '1893-S Morgan Dollar',
    year: 1893,
    mintMark: 'S',
    priceCents: 485000,
    shippingCents: 2500,
    imageUrl: '/listings/lst_001.jpg',
    graded: true,
    service: 'PCGS',
    grade: 'VF-20',
    certNumber: '90412263',
    description: 'The key-date Morgan with even grey wear and no rim issues.',
    createdAt: '2026-08-02T15:10:00Z',
  },
  {
    id: 'lst_002',
    sellerId: 'mike',
    category: 'coin',
    title: '1884-O Morgan Dollar',
    year: 1884,
    mintMark: 'O',
    priceCents: 8900,
    shippingCents: 500,
    imageUrl: '/listings/lst_002.jpg',
    graded: true,
    service: 'NGC',
    grade: 'MS-63',
    certNumber: '6612045-011',
    description: 'Bright New Orleans strike with a thin band of rim toning.',
    createdAt: '2026-08-11T18:42:00Z',
  },
  {
    id: 'lst_003',
    sellerId: 'mike',
    category: 'coin',
    title: '1943-D Mercury Dime',
    year: 1943,
    mintMark: 'D',
    priceCents: 2400,
    shippingCents: 0,
    imageUrl: '/listings/lst_003.png',
    graded: true,
    service: 'PCGS',
    grade: 'MS-66FB',
    certNumber: '90418870',
    description: 'Full split bands on the reverse and clean white surfaces.',
    createdAt: '2026-08-20T12:05:00Z',
  },
  {
    id: 'lst_004',
    sellerId: 'mike',
    category: 'coin',
    title: '1945-D Walking Liberty Half Dollar',
    year: 1945,
    mintMark: 'D',
    priceCents: 3200,
    shippingCents: 0,
    imageUrl: '/listings/lst_004.png',
    graded: false,
    description: 'Raw, lightly circulated, sharp detail in the skirt lines.',
    createdAt: '2026-09-01T09:30:00Z',
  },
  {
    id: 'lst_005',
    sellerId: 'sel_bluesheet',
    category: 'coin',
    title: '1889-P Morgan Dollar',
    year: 1889,
    mintMark: 'P',
    priceCents: 7500,
    shippingCents: 500,
    imageUrl: '/listings/lst_005.png',
    graded: true,
    service: 'PCGS',
    grade: 'MS-64',
    certNumber: '90407719',
    description: 'Philadelphia common date with good luster and light chatter.',
    createdAt: '2026-07-14T14:00:00Z',
  },
  {
    id: 'lst_006',
    sellerId: 'sel_bluesheet',
    category: 'coin',
    title: '1922 Peace Dollar',
    year: 1922,
    priceCents: 4800,
    shippingCents: 500,
    imageUrl: '/listings/lst_006.jpg',
    graded: true,
    service: 'NGC',
    grade: 'MS-64',
    certNumber: '6608312-002',
    description: 'Satiny low-relief Peace dollar with a clean cheek.',
    createdAt: '2026-07-19T16:25:00Z',
  },
  {
    id: 'lst_007',
    sellerId: 'sel_bluesheet',
    category: 'coin',
    title: '2004 American Silver Eagle',
    year: 2004,
    priceCents: 5600,
    shippingCents: 0,
    imageUrl: '/listings/lst_007.png',
    graded: true,
    service: 'NGC',
    grade: 'MS-69',
    certNumber: '6619927-040',
    description: 'One-ounce bullion eagle, near-flawless and free of milk spots.',
    createdAt: '2026-08-28T10:15:00Z',
  },
  {
    id: 'lst_008',
    sellerId: 'sel_carsoncity',
    category: 'coin',
    title: '1921 Peace Dollar, High Relief',
    year: 1921,
    priceCents: 42500,
    shippingCents: 1200,
    imageUrl: '/listings/lst_008.jpg',
    graded: true,
    service: 'PCGS',
    grade: 'AU-58',
    certNumber: '90401156',
    description: 'First-year high relief with a touch of wear on the hair curls.',
    createdAt: '2026-06-30T20:45:00Z',
  },
  {
    id: 'lst_009',
    sellerId: 'sel_carsoncity',
    category: 'coin',
    title: '1940-S Walking Liberty Half Dollar',
    year: 1940,
    mintMark: 'S',
    priceCents: 6500,
    shippingCents: 500,
    imageUrl: '/listings/lst_009.jpg',
    graded: true,
    service: 'PCGS',
    grade: 'MS-62',
    certNumber: '90415502',
    description: 'Typical soft San Francisco strike, fully original surfaces.',
    createdAt: '2026-08-05T11:20:00Z',
  },
  {
    id: 'lst_010',
    sellerId: 'sel_carsoncity',
    category: 'coin',
    title: '1917-S Standing Liberty Quarter, Type 1',
    year: 1917,
    mintMark: 'S',
    priceCents: 27500,
    shippingCents: 800,
    imageUrl: '/listings/lst_010.png',
    graded: true,
    service: 'NGC',
    grade: 'XF-45',
    certNumber: '6603348-007',
    description: 'Type 1 with a partial date and honest, even circulation.',
    createdAt: '2026-08-14T13:55:00Z',
  },
  {
    id: 'lst_011',
    sellerId: 'sel_wheatieshunter',
    category: 'coin',
    title: '1909-S VDB Lincoln Cent',
    year: 1909,
    mintMark: 'S',
    priceCents: 165000,
    shippingCents: 1500,
    imageUrl: '/listings/lst_011.jpg',
    graded: true,
    service: 'PCGS',
    grade: 'VF-30',
    certNumber: '90409934',
    description: 'The first-year Lincoln key in chocolate brown, no cleaning.',
    createdAt: '2026-07-08T17:30:00Z',
  },
  {
    id: 'lst_012',
    sellerId: 'sel_wheatieshunter',
    category: 'coin',
    title: '1888 Indian Head Cent',
    year: 1888,
    priceCents: 2000,
    shippingCents: 0,
    imageUrl: '/listings/lst_012.jpg',
    graded: false,
    description: 'Raw circulated cent with full LIBERTY on the headband.',
    createdAt: '2026-09-04T08:10:00Z',
  },
  {
    id: 'lst_013',
    sellerId: 'sel_wheatieshunter',
    category: 'coin',
    title: '1935 Buffalo Nickel',
    year: 1935,
    priceCents: 2800,
    shippingCents: 0,
    imageUrl: '/listings/lst_013.jpg',
    graded: true,
    service: 'NGC',
    grade: 'MS-64',
    certNumber: '6615520-019',
    description: 'Full date and a well-struck horn on the bison.',
    createdAt: '2026-08-22T19:00:00Z',
  },
  {
    id: 'lst_014',
    sellerId: 'sel_doubleeagle',
    category: 'coin',
    title: '1908 Saint-Gaudens Double Eagle, No Motto',
    year: 1908,
    priceCents: 289000,
    shippingCents: 2500,
    imageUrl: '/listings/lst_014.jpg',
    graded: true,
    service: 'PCGS',
    grade: 'MS-65',
    certNumber: '90403381',
    description: 'Gem no-motto twenty with rich orange-gold luster.',
    createdAt: '2026-06-18T15:40:00Z',
  },
  {
    id: 'lst_015',
    sellerId: 'sel_doubleeagle',
    category: 'coin',
    title: '1907 Saint-Gaudens Double Eagle, High Relief',
    year: 1907,
    priceCents: 598000,
    shippingCents: 2500,
    imageUrl: '/listings/lst_015.jpg',
    graded: true,
    service: 'NGC',
    grade: 'AU-55',
    certNumber: '6600417-001',
    description: 'Wire-rim high relief with light rub on Liberty’s knee.',
    createdAt: '2026-07-01T12:00:00Z',
  },
  {
    id: 'lst_016',
    sellerId: 'sel_attictreasure',
    category: 'coin',
    title: '1963-D Franklin Half Dollar',
    year: 1963,
    mintMark: 'D',
    priceCents: 2200,
    shippingCents: 400,
    imageUrl: '/listings/lst_016.png',
    graded: false,
    description: 'Raw uncirculated-looking Franklin from a family roll.',
    createdAt: '2026-09-10T21:15:00Z',
  },
  {
    id: 'lst_017',
    sellerId: 'sel_attictreasure',
    category: 'coin',
    title: 'Mercury Dime, Date Worn',
    priceCents: 2000,
    shippingCents: 400,
    imageUrl: '/listings/lst_017.jpg',
    graded: false,
    description: 'Raw 90% silver dime with a worn date, sold as-is.',
    createdAt: '2026-09-12T10:00:00Z',
  },

  // ── Cards ────────────────────────────────────────────────────────────────
  card({
    id: 'lst_018',
    sellerId: 'sel_rookiecards',
    short: '1989 Rookie Card #1',
    title: '1989 Upper Deck #1 Rookie Card',
    year: 1989,
    priceCents: 34900,
    shippingCents: 600,
    graded: true,
    service: 'PSA',
    grade: 'PSA 9',
    certNumber: '80011427',
    description: 'Well-centered copy of the headline card from the set.',
    createdAt: '2026-07-22T14:30:00Z',
  }),
  card({
    id: 'lst_019',
    sellerId: 'sel_rookiecards',
    short: '2011 Update #US175',
    title: '2011 Topps Update #US175 Rookie Card',
    year: 2011,
    priceCents: 129900,
    shippingCents: 800,
    graded: true,
    service: 'PSA',
    grade: 'PSA 10',
    certNumber: '80023318',
    description: 'Gem mint base rookie with sharp corners under the slab.',
    createdAt: '2026-08-03T16:05:00Z',
  }),
  card({
    id: 'lst_020',
    sellerId: 'sel_rookiecards',
    short: '2018 Chrome #150',
    title: '2018 Topps Chrome #150 Rookie Card',
    year: 2018,
    priceCents: 18500,
    shippingCents: 600,
    graded: true,
    service: 'BGS',
    grade: 'BGS 9.5',
    certNumber: '0011874523',
    description: 'Chrome rookie with a 9.5 centering sub-grade.',
    createdAt: '2026-08-25T09:50:00Z',
  }),
  card({
    id: 'lst_021',
    sellerId: 'sel_rookiecards',
    short: '1987 Topps #320',
    title: '1987 Topps #320 Rookie Card',
    year: 1987,
    priceCents: 2500,
    shippingCents: 0,
    graded: false,
    description: 'Raw rookie pulled from a binder, soft top-left corner.',
    createdAt: '2026-09-08T18:20:00Z',
  }),
  card({
    id: 'lst_022',
    sellerId: 'sel_hoopslabs',
    short: '2003 Topps #221',
    title: '2003-04 Topps #221 Rookie Card',
    year: 2003,
    priceCents: 89500,
    shippingCents: 1000,
    graded: true,
    service: 'PSA',
    grade: 'PSA 9',
    certNumber: '80037752',
    description: 'Base rookie with clean edges and slight left-right tilt.',
    createdAt: '2026-07-27T20:10:00Z',
  }),
  card({
    id: 'lst_023',
    sellerId: 'sel_hoopslabs',
    short: '2019 Prizm #248',
    title: '2019-20 Panini Prizm #248 Rookie Card',
    year: 2019,
    priceCents: 6900,
    shippingCents: 500,
    graded: true,
    service: 'CGC',
    grade: 'CGC 9.5',
    certNumber: '4127730012',
    description: 'Silver-border base Prizm rookie in a CGC holder.',
    createdAt: '2026-08-17T13:35:00Z',
  }),
  card({
    id: 'lst_024',
    sellerId: 'mike',
    short: '1996 Topps Chrome #138',
    title: '1996-97 Topps Chrome #138 Rookie Card',
    year: 1996,
    priceCents: 112500,
    shippingCents: 1000,
    graded: true,
    service: 'PSA',
    grade: 'PSA 8',
    certNumber: '80042286',
    description: 'Chrome rookie with minor surface lines visible at an angle.',
    createdAt: '2026-08-29T15:15:00Z',
  }),
  card({
    id: 'lst_025',
    sellerId: 'sel_holofoil',
    short: '1999 Base Set #4 Holo',
    title: '1999 Pokémon Base Set Charizard Holo #4/102',
    year: 1999,
    priceCents: 425000,
    shippingCents: 2000,
    graded: true,
    service: 'PSA',
    grade: 'PSA 8',
    certNumber: '80055190',
    description: 'Unlimited Base Set Charizard with strong holo and light whitening.',
    createdAt: '2026-06-25T19:25:00Z',
  }),
  card({
    id: 'lst_026',
    sellerId: 'sel_holofoil',
    short: '1999 Base Set #58',
    title: '1999 Pokémon Base Set Pikachu #58/102',
    year: 1999,
    priceCents: 3500,
    shippingCents: 400,
    graded: true,
    service: 'CGC',
    grade: 'CGC 9',
    certNumber: '4127745530',
    description: 'Yellow-cheeks Pikachu with bright color and square corners.',
    createdAt: '2026-08-08T11:40:00Z',
  }),
  card({
    id: 'lst_027',
    sellerId: 'sel_holofoil',
    short: '2016 Evolutions #11',
    title: '2016 Pokémon XY Evolutions Charizard Holo #11/108',
    year: 2016,
    priceCents: 9500,
    shippingCents: 400,
    graded: true,
    service: 'BGS',
    grade: 'BGS 9.5',
    certNumber: '0011902267',
    description: 'Modern Base Set tribute holo with a clean, scratch-free surface.',
    createdAt: '2026-08-19T17:55:00Z',
  }),
  card({
    id: 'lst_028',
    sellerId: 'sel_holofoil',
    short: '1999 Jungle #11 Holo',
    title: '1999 Pokémon Jungle Snorlax Holo #11/64',
    year: 1999,
    priceCents: 4200,
    shippingCents: 400,
    graded: false,
    description: 'Raw holo from a childhood binder, light edge wear on the back.',
    createdAt: '2026-09-06T12:45:00Z',
  }),
  card({
    id: 'lst_029',
    sellerId: 'sel_attictreasure',
    short: '1952 Topps #311',
    title: '1952 Topps #311',
    year: 1952,
    priceCents: 595000,
    shippingCents: 2500,
    graded: true,
    service: 'PSA',
    grade: 'PSA 1',
    certNumber: '80060041',
    description: 'Authentic low-grade copy with creasing but full, unaltered borders.',
    createdAt: '2026-09-13T16:00:00Z',
  }),
  card({
    id: 'lst_030',
    sellerId: 'sel_hoopslabs',
    short: '1986 Fleer #57',
    title: '1986-87 Fleer #57 Rookie Card',
    year: 1986,
    priceCents: 345000,
    shippingCents: 2000,
    graded: true,
    service: 'BGS',
    grade: 'BGS 7',
    certNumber: '0011930048',
    description: 'Iconic rookie with visible off-centering and solid corners.',
    createdAt: '2026-07-11T10:30:00Z',
  }),
]
